---
- name: create a sandbox instance
  hosts: localhost
  gather_facts: false
  vars:
   keypair: key
   instance_type: t2.micro
   image: ami-89e74cea
   region: ap-southeast-1
  tasks:
    - name: launch instance
      ec2:
          key_name: "{{ keypair }}"
          group: default
          instance_type: "{{ instance_type }}"
          image: "{{ image }}"
          wait: true
          region: "{{ region }}"
          aws_access_key: AKIAJF4JBPEZUZBT5WUQ
          aws_secret_key: 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
      register: ec2
    - name: print all ec2 variables
      debug: var=ec2